import { useState, useEffect } from 'react'
import {
  CloseOutlined,
  UserOutlined,
  LockOutlined,
  IdcardOutlined,
  TeamOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  LoadingOutlined,
} from '@ant-design/icons'
import './AddEmployeeDrawer.css'

interface FormData {
  full_name: string
  username: string
  password: string
  role: string
}

interface Props {
  open: boolean
  onClose: () => void
  onSuccess: () => void
}

const ROLE_OPTIONS = [
  'employee',
  'admin',
]

const INITIAL_FORM: FormData = {
  full_name: '',
  username: '',
  password: '',
  role: '',
}

/** Loại bỏ dấu tiếng Việt */
function removeVietnameseTones(str: string): string {
  return str
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
}

/**
 * Tạo username từ họ tên:
 * VD: "Nguyễn Văn An" → "an.nv" + 4 chữ số ngẫu nhiên → "an.nv3947"
 * Đảm bảo ít trùng nhất có thể
 */
function generateUsername(fullName: string): string {
  const cleaned = removeVietnameseTones(fullName).toLowerCase()
  const parts = cleaned.split(/\s+/).filter(Boolean)
  if (parts.length === 0) return ''

  // Tên (từ cuối cùng theo thứ tự tên người Việt)
  const firstName = parts[parts.length - 1]

  // Viết tắt họ + đệm (các từ còn lại, lấy chữ cái đầu)
  const abbrev = parts.slice(0, -1).map(p => p[0]).join('')

  // Base: "tên.viếttắt"
  const base = abbrev ? `${firstName}.${abbrev}` : firstName

  // 4 chữ số ngẫu nhiên (1000–9999)
  const rand = Math.floor(1000 + Math.random() * 9000)

  return `${base}${rand}`.replace(/[^a-z0-9_.]/g, '')
}

export default function AddEmployeeDrawer({ open, onClose, onSuccess }: Props) {
  const [form, setForm] = useState<FormData>(INITIAL_FORM)
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({})
  const [showPassword, setShowPassword] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)
  // true = username do hệ thống tạo (chưa chỉnh tay)
  const [usernameAutoGenerated, setUsernameAutoGenerated] = useState(true)

  // Reset form khi đóng/mở lại
  useEffect(() => {
    if (open) {
      setForm(INITIAL_FORM)
      setErrors({})
      setSubmitError(null)
      setShowPassword(false)
      setUsernameAutoGenerated(true)
    }
  }, [open])

  // Đóng drawer khi nhấn ESC
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    if (open) document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [open, onClose])

  const set = (field: keyof FormData, value: string | boolean) => {
    setForm(prev => ({ ...prev, [field]: value }))
    if (errors[field]) setErrors(prev => ({ ...prev, [field]: undefined }))
  }

  /** Xử lý nhập họ tên → tự sinh username nếu chưa bị chỉnh tay */
  const handleFullNameChange = (value: string) => {
    setForm(prev => {
      const newForm = { ...prev, full_name: value }
      if (usernameAutoGenerated) {
        newForm.username = generateUsername(value)
      }
      return newForm
    })
    if (errors.full_name) setErrors(prev => ({ ...prev, full_name: undefined }))
    if (usernameAutoGenerated && errors.username)
      setErrors(prev => ({ ...prev, username: undefined }))
  }

  /** Khi user tự chỉnh username → ngừng auto-gen */
  const handleUsernameChange = (value: string) => {
    setUsernameAutoGenerated(false)
    set('username', value.toLowerCase())
  }

  /** Sinh lại username mới (nút refresh) */
  const regenerateUsername = () => {
    if (form.full_name.trim()) {
      setForm(prev => ({ ...prev, username: generateUsername(form.full_name) }))
      setUsernameAutoGenerated(true)
      if (errors.username) setErrors(prev => ({ ...prev, username: undefined }))
    }
  }

  const validate = (): boolean => {
    const newErrors: Partial<Record<keyof FormData, string>> = {}
    if (!form.full_name.trim()) newErrors.full_name = 'Vui lòng nhập họ và tên'
    if (!form.role) newErrors.role = 'Vui lòng chọn vai trò'
    if (!form.username.trim()) newErrors.username = 'Vui lòng nhập username'
    else if (!/^[a-zA-Z0-9_.]{3,30}$/.test(form.username))
      newErrors.username = 'Username chỉ gồm chữ, số, dấu chấm hoặc gạch dưới (3–30 ký tự)'
    if (!form.password) newErrors.password = 'Vui lòng nhập mật khẩu'
    else if (form.password.length < 6) newErrors.password = 'Mật khẩu tối thiểu 6 ký tự'
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!validate()) return
    setSubmitting(true)
    setSubmitError(null)
    try {
      const res = await fetch('http://localhost:3001/api/employees/add', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          full_name: form.full_name.trim(),
          username: form.username.trim(),
          password: form.password,
          role: form.role,
        }),
      })
      const json = await res.json()
      if (!res.ok || !json.success) throw new Error(json.message || 'Tạo nhân viên thất bại')
      onSuccess()
      onClose()
    } catch (err: unknown) {
      setSubmitError(err instanceof Error ? err.message : 'Lỗi không xác định')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <>
      {/* Overlay */}
      <div
        className={`drawer-overlay ${open ? 'drawer-overlay-visible' : ''}`}
        onClick={onClose}
      />

      {/* Drawer panel */}
      <div className={`drawer-panel ${open ? 'drawer-panel-open' : ''}`}>
        {/* Header */}
        <div className="drawer-header">
          <div className="drawer-header-left">
            <div className="drawer-header-icon">
              <UserOutlined />
            </div>
            <div>
              <h2 className="drawer-title">Thêm nhân viên</h2>
              <p className="drawer-subtitle">Điền thông tin để tạo tài khoản nhân viên mới</p>
            </div>
          </div>
          <button className="drawer-close-btn" onClick={onClose} title="Đóng">
            <CloseOutlined />
          </button>
        </div>

        {/* Body / Form */}
        <form className="drawer-body" onSubmit={handleSubmit} noValidate>

          {/* Full name */}
          <div className="form-group">
            <label className="form-label">
              <IdcardOutlined /> Họ và tên <span className="required">*</span>
            </label>
            <input
              className={`form-input ${errors.full_name ? 'form-input-error' : ''}`}
              type="text"
              placeholder="VD: Nguyễn Văn An"
              value={form.full_name}
              onChange={e => handleFullNameChange(e.target.value)}
              autoFocus
            />
            {errors.full_name && <span className="form-error">{errors.full_name}</span>}
          </div>

          {/* Role */}
          <div className="form-group">
            <label className="form-label">
              <TeamOutlined /> Vai trò <span className="required">*</span>
            </label>
            <div className="form-select-wrap">
              <select
                className={`form-select ${errors.role ? 'form-input-error' : ''}`}
                value={form.role}
                onChange={e => set('role', e.target.value)}
              >
                <option value="">-- Chọn vai trò --</option>
                {ROLE_OPTIONS.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
            </div>
            {errors.role && <span className="form-error">{errors.role}</span>}
          </div>

          <div className="form-divider">
            <span>Thông tin đăng nhập</span>
          </div>

          {/* Username */}
          <div className="form-group">
            <label className="form-label">
              <UserOutlined /> Username <span className="required">*</span>
            </label>
            <div className="username-input-wrap">
              <input
                className={`form-input username-input ${errors.username ? 'form-input-error' : ''}`}
                type="text"
                placeholder="Tự động sinh từ họ tên..."
                value={form.username}
                onChange={e => handleUsernameChange(e.target.value)}
                autoComplete="off"
              />
              {form.full_name.trim() && (
                <button
                  type="button"
                  className={`username-regen-btn ${usernameAutoGenerated ? 'username-regen-auto' : ''}`}
                  onClick={regenerateUsername}
                  title="Sinh lại username mới"
                >
                  🔄
                </button>
              )}
            </div>
            {errors.username && <span className="form-error">{errors.username}</span>}
          </div>

          {/* Password */}
          <div className="form-group">
            <label className="form-label">
              <LockOutlined /> Mật khẩu <span className="required">*</span>
            </label>
            <div className="form-input-wrap">
              <input
                className={`form-input form-input-pw ${errors.password ? 'form-input-error' : ''}`}
                type={showPassword ? 'text' : 'password'}
                placeholder="Tối thiểu 6 ký tự"
                value={form.password}
                onChange={e => set('password', e.target.value)}
                autoComplete="new-password"
              />
              <button
                type="button"
                className="pw-toggle"
                onClick={() => setShowPassword(p => !p)}
                tabIndex={-1}
              >
                {showPassword ? <EyeInvisibleOutlined /> : <EyeOutlined />}
              </button>
            </div>
            {errors.password && <span className="form-error">{errors.password}</span>}
          </div>

          {/* API error */}
          {submitError && (
            <div className="form-api-error">
              ⚠️ {submitError}
            </div>
          )}

          {/* Footer buttons */}
          <div className="drawer-footer">
            <button type="button" className="btn-cancel" onClick={onClose} disabled={submitting}>
              Huỷ bỏ
            </button>
            <button type="submit" className="btn-submit" disabled={submitting}>
              {submitting
                ? <><LoadingOutlined spin /> Đang tạo...</>
                : <><UserOutlined /> Thêm nhân viên</>
              }
            </button>
          </div>
        </form>
      </div>
    </>
  )
}
